# Travis CI config file
# https://docs.travis-ci.com/

dist: xenial

language: node_js

node_js:
  - "11.*"
  - "10.*"
  - "9.*"
  - "8.*"
  - "7.*"

cache:
  yarn: true

install:
  - yarn --ignore-engines # AVA is not officially supported on Node.js 7.x and 9.x

script:
  - yarn test
