name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # note: Yarn in pre-installed in the VM image
      # (see https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)
      - name: Install dependencies
        # optionally use yarn --ignore-engines
        run: yarn
      - name: Run tests
        run: yarn test
